### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by PBOwner** [DeclanChidlow/AutoMod#4]
I get 99 levels of issues when trying to start the bot

```bash
bot-1    | INFO  $API_WS_URL and $API_WS_TOKEN set; Connecting to ws://api:9000/internal/ws
bot-1    | INFO  Connection state: Connecting
bot-1    | ERROR WebSocket error: connect ECONNREFUSED IP:9000```

```bash
bot-1    | WARN  Failed to run migrations for infractions: MongoError: ns does not exist: admin.infractions
bot-1    | WARN  Failed to run migrations for pending_logins: MongoError: ns does not exist: admin.pending_logins
bot-1    | WARN  Failed to run migrations for servers: MongoError: ns does not exist: admin.servers
bot-1    | WARN  Failed to run migrations for sessions: MongoError: ns does not exist: admin.sessions
bot-1    | WARN  Failed to run migrations for tempbans: MongoError: ns does not exist: admin.tempbans
bot-1    | WARN  Failed to run migrations for users: MongoError: ns does not exist: admin.users
bot-1    | WARN  Failed to run migrations for votekicks: MongoError: ns does not exist: admin.votekicks```

```bash
api-1    | INFO  Listening on port 9000
api-1    | ECONNREFUSED: Failed to connect
api-1    |    errno: 24
api-1    |  syscall: "connect"```

**Comment by DeclanChidlow** [comment]
Hey, this issue has been fixed. Feel welcome to clone the repository again and give it another go.

https://github.com/DeclanChidlow/AutoMod/wiki/Self-Hosting

**Comment by PBOwner** [comment]
I'm getting a different issue now.
```bot-1    | (node:35) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
bot-1    | DONE  DB ready!
bot-1    | INFO  Running database migrations...
bot-1    | WARN  Failed to run migrations for infractions: MongoError: ns does not exist: admin.infractions
bot-1    | WARN  Failed to run migrations for pending_logins: MongoError: ns does not exist: admin.pending_logins
bot-1    | WARN  Failed to run migrations for sessions: MongoError: ns does not exist: admin.sessions
bot-1    | WARN  Failed to run migrations for tempbans: MongoError: ns does not exist: admin.tempbans
bot-1    | WARN  Failed to run migrations for users: MongoError: ns does not exist: admin.users
bot-1    | WARN  Failed to run migrations for votekicks: MongoError: ns does not exist: admin.votekicks
bot-1    | INFO  Enabling Prometheus metrics on :0
bot-1    | DONE  Prometheus metrics ready
bot-1    | INFO  $API_WS_URL and $API_WS_TOKEN set; Connecting to ws://api:9000/internal/ws
bot-1    | INFO  Connection state: Connecting
api-1    | DEBUG WS Upgrade /internal/ws
bot-1    | INFO  WebSocket connected successfully
bot-1    | DONE  Bot logged in as FuturoMod!
bot-1    | INFO  Connection state: Connected
bot-1    | INFO  Starting to fetch users in 1 servers.
mongo-1  | {"t":{"$date":"2024-08-19T21:46:33.868+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.20.0.5:32882","uuid":{"uuid":{"$uuid":"1c170ab2-dc48-49f5-956b-83b77cd6a4b5"}},"connectionId":5,"connectionCount":5}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:33.896+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"172.20.0.5:32882","client":"conn5","negotiatedCompressors":[],"doc":{"driver":{"name":"nodejs","version":"3.7.3"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-113-fips"},"platform":"'Node.js v18.20.4, LE (unified)"}}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:33.896+00:00"},"s":"I",  "c":"ACCESS",   "id":6788604, "ctx":"conn5","msg":"Auth metrics report","attr":{"metric":"acquireUser","micros":0}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:33.900+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn5","msg":"Successfully authenticated","attr":{"client":"172.20.0.5:32882","isSpeculative":true,"isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"mogus","db":"admin","result":0,"metrics":{"conversation_duration":{"micros":3933,"summary":{"0":{"step":1,"step_total":2,"duration_micros":78},"1":{"step":2,"step_total":2,"duration_micros":36}}}},"extraInfo":{}}}
bot-1    | DONE  Downloaded all users from 1 servers with 0 errors. Cache size: 6
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104001181.9235592","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104001181.9235592","type":"response:1724104001181.9235592","data":{"servers":1}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:42.213+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.20.0.4:38954","uuid":{"uuid":{"$uuid":"810c1574-f80f-4532-982d-08dde700cf2c"}},"connectionId":6,"connectionCount":6}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:42.220+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"172.20.0.4:38954","client":"conn6","negotiatedCompressors":[],"doc":{"driver":{"name":"nodejs","version":"6.8.0"},"platform":"Bun v1.1.24, LE","os":{"name":"linux","architecture":"x64","version":"5.15.0-113-fips","type":"Linux"},"env":{"container":{"runtime":"docker"}}}}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:42.944+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.20.0.5:56438","uuid":{"uuid":{"$uuid":"654adb6e-989e-43e8-8a6c-9aecad9f7a55"}},"connectionId":7,"connectionCount":7}}
mongo-1  | {"t":{"$date":"2024-08-19T21:46:42.947+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn7","msg":"client metadata","attr":{"remote":"172.20.0.5:56438","client":"conn7","negotiatedCompressors":[],"doc":{"driver":{"name":"nodejs","version":"3.7.3"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-113-fips"},"platform":"'Node.js v18.20.4, LE (unified)"}}}
api-1    | DEBUG GET /
api-1    | TypeError: next is not a function. (In 'next()', 'next' is an instance of Object)
api-1    |     at <anonymous> (/app/api/src/middlewares/log.ts:6:5)
api-1    |     at handle (/app/api/node_modules/express/lib/router/layer.js:95:5)
api-1    |     at trim_prefix (/app/api/node_modules/express/lib/router/index.js:328:13)
api-1    |     at <anonymous> (/app/api/node_modules/express/lib/router/index.js:286:9)
api-1    |     at process_params (/app/api/node_modules/express/lib/router/index.js:421:3)
api-1    |     at next (/app/api/node_modules/express/lib/router/index.js:280:10)
api-1    |     at jsonParser (/app/api/node_modules/body-parser/lib/types/json.js:113:7)
api-1    |     at handle (/app/api/node_modules/express/lib/router/layer.js:95:5)
api-1    |     at trim_prefix (/app/api/node_modules/express/lib/router/index.js:328:13)
api-1    |     at <anonymous> (/app/api/node_modules/express/lib/router/index.js:286:9)
api-1    |     at next (/app/api/node_modules/express/lib/router/index.js:280:10)
api-1    |     at expressInit (/app/api/node_modules/express/lib/middleware/init.js:40:5)
api-1    |     at handle (/app/api/node_modules/express/lib/router/layer.js:95:5)
api-1    |     at trim_prefix (/app/api/node_modules/express/lib/router/index.js:328:13)
api-1    |     at <anonymous> (/app/api/node_modules/express/lib/router/index.js:286:9)
api-1    |     at next (/app/api/node_modules/express/lib/router/index.js:280:10)
api-1    |     at query (/app/api/node_modules/express/lib/middleware/query.js:45:5)
api-1    |     at handle (/app/api/node_modules/express/lib/router/layer.js:95:5)
api-1    |     at trim_prefix (/app/api/node_modules/express/lib/router/index.js:328:13)
api-1    |     at <anonymous> (/app/api/node_modules/express/lib/router/index.js:286:9)
api-1    |     at next (/app/api/node_modules/express/lib/router/index.js:280:10)
api-1    |     at handle (/app/api/node_modules/express/lib/router/index.js:175:3)
api-1    |     at handle (/app/api/node_modules/express/lib/application.js:181:10)
api-1    |     at app (/app/api/node_modules/express/lib/express.js:39:9)
api-1    |     at emit (node:events:180:48)
api-1    |     at fetch (node:http:492:14)
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104011182.1176989","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104011182.1176989","type":"response:1724104011182.1176989","data":{"servers":1}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104021179.9659935","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104021179.9659935","type":"response:1724104021179.9659935","data":{"servers":1}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104031179.1520182","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104031179.1520182","type":"response:1724104031179.1520182","data":{"servers":1}}
mongo-1  | {"t":{"$date":"2024-08-19T21:47:13.865+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn5","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":39964}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104041180.8629605","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104041180.8629605","type":"response:1724104041180.8629605","data":{"servers":1}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104051180.4005191","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104051180.4005191","type":"response:1724104051180.4005191","data":{"servers":1}}
mongo-1  | {"t":{"$date":"2024-08-19T21:47:31.552+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1724104051,"ts_usec":552367,"thread":"1:0x7f57c3088640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 4, snapshot max: 4 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 29"}}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104061181.9235430","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104061181.9235430","type":"response:1724104061181.9235430","data":{"servers":1}}
api-1    | DEBUG [WS] [>] [1] {"nonce":"1724104071181.604404","type":"stats"}
api-1    | DEBUG [WS] [<] {"nonce":"1724104071181.604404","type":"response:1724104071181.604404","data":{"servers":1}}```

**Comment by PBOwner** [comment]
I am unable to load the site up, but the bot is responding at least

**Comment by DeclanChidlow** [comment]
Hey, I've fixed this locally but haven't published the fix just yet. Ensure you're using the 'stable' branch, as that has the most up to date release with fixes.

Hoping to get the fix out tonight.

**Comment by DeclanChidlow** [comment]
These issues should have been long since fixed.
